server:
  port: 8081

spring:
  application:
    name: test-nacos-provider-sever
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 80811
        dashboard: 127.0.0.1:8088