server:
  port: 9002

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 9022
        dashboard: 127.0.0.1:8849

feign:
  sentinel:
    enabled: true

logging:
  level:
    cn:
      hellozuofeng:
        nacosdemo:
          client:
            ProviderClient: debug